$(".slide-items").slick({
  autoplay:true,
  autoplaySpeed:2500,
  speed:800,
  infinite:true,
  centerMode:true,
  centerPadding:'20%',
  arrows:false,
  dots:true,
  pauseOnHover:false,
});